name: NodeJS Docker Compose CI/CD

on:
  push:
    branches:
      - main
jobs:
  deploy:   
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd stop-watch-app
            git pull origin main
