name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo testing

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          echo building

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
          
      - name: Deploy to Ec2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |  
            cd stop-watch-app
            git pull origin
            cd
            sudo cp -r stop-watch-app/* /var/www/html
            sudo systemctl restart nginx